# Generated by Django 4.2.2 on 2023-06-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obsequiar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
